### PR TITLE
feat: support jakarta jsp

### LINKED ISSUE #64: Any plans for a version using Jakarta Servlet 5.0?
We are currently migrating our Spring Boot application to version 3.0.

In [Spring Boot 3.0 they've migrated all dependencies from Java EE to Jakarta EE APIs](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee). Now Jakarta EE 10 dependencies are used.

We are using the OWASP Java Encoder library and specifically the JSP module to encode user input. For example:
```
<%@ taglib prefix="e" uri="https://www.owasp.org/index.php/OWASP_Java_Encoder_Project" %>
<e:forHtml value="${user.name}" />
```
This is causing the following error:
```
java.lang.ClassNotFoundException: javax.servlet.jsp.tagext.SimpleTagSupport
```

This is because we are now using Jakarta Servlet 5.0 and the packages have been changed from `javax.*` to `jakarta.*`.
`javax.servlet.jsp.tagext.SimpleTagSupport` is now `jakarta.servlet.jsp.tagext.SimpleTagSupport`.

Are there any plans for a version using Jakarta Servlet 5.0?

I noticed that there's [a discussion in the OWASP ESAPI project](https://github.com/ESAPI/esapi-java-legacy/discussions/768) which deals with the same problem.

### PR DESCRIPTION
**Pull request by jeremylong**
- resolves #64
- now requires java 8 for runtime
- requires jdk 17 to build due to jakarta module

Pretty sure a few other things need to be updated - like the readme.md... I'll try to get to this soon.

### CODE REVIEW

**Comment by kwwall** [comment]
@jeremylong  - ESAPI faced this simpler problem a while back. (E.g., see [ESAPI discussion 768](https://github.com/ESAPI/esapi-java-legacy/discussions/768)) Assuming that  you still wish to continue to support the older Servlet API spec that uses the `javax.servlet` namespace, but depending on your circumstances, there may be a better way than making all these changes. (This approach if fine if you okay with abandoning your  clients that are sill using the older Servlet API or want to maintain multiple forks or branches. We didn't want to do either for ESAPI.)

I played around with the Maven Shade plugin, but ruled that out as it created an uber jar that we didn't feel was acceptable. But then long story short, we ended up using the `org.eclipse.transformer:transformer-maven-plugin` plugin to just rewrite the byte-code. You  can see details [here in our pom](https://github.com/ESAPI/esapi-java-legacy/blob/develop/pom.xml#L942-L1010) and [here in our README](https://github.com/ESAPI/esapi-java-legacy?tab=readme-ov-file#jakarta-ee-support).

Now, given that you have Spring-Core 5.3.19 listed as a dependency in your jsp/pom.xml, this may not work for you, but I think it's certainly worth a shot. The ESAPI team is very happen with it and have heard no complaints yet about it. When we finally start on ESAPI 3, we will abandon support for the older Servlet API and only support the Jarkarta Servlet API 5.0 or later. But for now, we feel that we must support both of them. Of course, YMMV.

**Comment by jeremylong** [comment]
@kwwall I think you missed part of this PR - the legacy javax.servlet JAR will still be built and published. The only difference is that it will require at least Java 8 now - which shouldn't be a problem. A new jar will be produced that is Java 17 and uses the jakarta namespace for the servlet API.

**Comment by jeremylong** [comment]
Build passes - but fails on esapi thunk. Will be resolved with #76.

**Comment by jeremylong** [comment]
@jmanico any issues with these changes?

**Pull request merged**
